name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # ou master, selon le nom de votre branche principale

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Vous pouvez ajouter des étapes de build ici si vous voulez build sur le serveur
      # Mais si vous pushez déjà le dossier docs, vous pouvez simplement le déployer

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: docs  # Le dossier que vous avez généré localement
          branch: gh-pages  # La branche de déploiement
          clean: true  # Supprime les fichiers existants
